


select COURSE.COURSE_FRIENDLY, TIME_SLOT.DATE_TIME, USER_T.FIRST_NAME,
    USER_T.LAST_NAME, USER_T.EMAIL
    
    from USER_T, TIME_SLOT, COURSE
    
    where COURSE.COURSE_ID = TIME_SLOT.COURSE_ID and TIME_SLOT.STUDENT_HAWKID= 'awolmutt'
    and USER_T.HAWKID = TIME_SLOT.HAWKID; 
    