



select COURSE.COURSE_FRIENDLY, USER_T.FIRST_NAME, USER_T.LAST_NAME, USER_T.EMAIL, TIME_SLOT.DATE_TIME,
TIME_SLOT.COURSE_ID
from USER_T, TIME_SLOT, COURSE, ROLE_T 
where USER_T.HAWKID = TIME_SLOT.HAWKID and ROLE_T.HAWKID = 'awolmutt' and
COURSE.COURSE_ID = ROLE_T.COURSE_ID and TIME_SLOT.COURSE_ID = ROLE_T.COURSE_ID and
TIME_SLOT.IS_BOOKED = 0 and ROLE_T.DESCRIPTION = 'student'; 